---
name: "Customized git checkout for NX"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      name: Checkout [Pull Request]
      if: ${{ github.event_name == 'pull_request' }}
      with:
        # By default, PRs will be checked-out based on the Merge Commit, but we want the actual branch HEAD.
        ref: ${{ github.event.pull_request.head.sha }}
        # We need to fetch all branches and commits so that Nx affected has a base to compare against.
        fetch-depth: 0

    - uses: actions/checkout@v2
      name: Checkout [Default Branch]
      if: ${{ github.event_name != 'pull_request' }}
      with:
        # We need to fetch all branches and commits so that Nx affected has a base to compare against.
        fetch-depth: 0
